### ISSUE TITLE
Updated Makefile

### ISSUE THREAD

**Issue by hdamron17** [jyn514/lox#5]
Some makefile updates because I was trying to compile it and these changes seemed good.

[0001-Updated-makefile-to-be-less-redundant-and-to-split-b.patch.txt](https://github.com/jyn514/lox/files/2673771/0001-Updated-makefile-to-be-less-redundant-and-to-split-b.patch.txt)

**Comment by hdamron17** [comment]
I missed that I missed a dependency to the generated source files so here's an updated patch. (It's .txt because GitHub wouldn't let me upload it otherwise.)

[0001-Updated-makefile-to-be-less-redundant-and-to-split-b.patch.txt](https://github.com/jyn514/lox/files/2673902/0001-Updated-makefile-to-be-less-redundant-and-to-split-b.patch.txt)

**Comment by hdamron17** [comment]
Also this patch is compatible with both OpenJDK and Oracle JDK although Oracle complains about `warning: [options] bootstrap class path not set in conjunction with -source 9`. The source and target 9 ensures the user is running java 9 instead of getting weird issues about what's missing in previous versions.

**Comment by jyn514** [comment]
In the future it would be nice if this were full pull request, so I could use github's native commenting.

> +JAVACFLAGS = -Xlint:all -g -target 9 -source 9 -d $(BUILD)

Making Java 9 explicitly required is a great move, thanks. I agree the build failures before were non-intuitive.

> +export DIST = dist

If you're going to change it, you should change it consistently. That said, I don't want this to be configurable because of the `include`d makefile; you wouldn't be able to change the `dest` directory from within the top-level makefile, you would have to move around other things on the filesystem. That level of customization is not something I want to deal with right now.

Also, in general don't use `export` unless you need to, it passes it as environment variable to subprocesses. CLASSPATH is exported because I'm lazy and don't want to add it to both JAVAFLAGS and JAVACFLAGS.
I think I'll change that now actually.

> +TMP = $(DIST)/tmp

Again, we can't have things configurable in the makefile if they're hardcoded elsewhere (in this case in the .gitignore).

> +       printf '#!/bin/sh\njava $(JAVAFLAGS) $(MAINJ) "$$@"' > jlox

This uses class files in the source directory, not in `$(BUILD)`. It worked for you because you added $(BUILD) to CLASSPATH. I kind of like the idea so I'm going to remove the current directory from CLASSPATH.

> +clean: distclean

This is not how the clean rules go, it's clean -> clobber -> distclean. 
https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets

Going to add most of this on my end, thanks for the patch.

**Comment by jyn514** [comment]
merged in https://github.com/jyn514/lox/commit/c8ce98b1726d5e99442bea53bc4f3af20c28dc66
